name: Build

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'build') }}

  required-status-check:
    needs:
      - common
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: needs.common.result != 'success'
        run: exit 1
