name: Build

on:
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/build-common.yml

  required-status-check:
    needs:
      - common
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: needs.common.result != 'success'
        run: exit 1
