name: Reusable - Create docs pull request

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      AARON_MAXWELL_TOKEN:
        required: true
  # to help with partial release build failures
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  create-docs-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: AaronMaxwell/azure-docs-pr
          # this is the personal access token used for "git push" below
          token: ${{ secrets.AARON_MAXWELL_TOKEN }}

      - name: Initialize pull request branch
        env:
          VERSION: ${{ inputs.version }}
        run: |
          git remote add upstream https://github.com/MicrosoftDocs/azure-docs-pr.git
          git fetch upstream main
          git checkout -b update-applicationinsights-java-to-${VERSION} upstream/main

      - name: Update version in docs
        env:
          VERSION: ${{ inputs.version }}
        run: |
          grep -rl applicationinsights-agent-[0-9.]*.jar articles/azure-monitor/app \
            | xargs sed -Ei "/applicationinsights-agent-2\./! s/applicationinsights-agent-[0-9.]+.jar/applicationinsights-agent-${VERSION}.jar/g"
          grep -rl applicationinsights-agent-[0-9.]*.jar articles/azure-monitor/app \
            | xargs sed -Ei "s|microsoft/ApplicationInsights-Java/releases/download/[0-9.]*/|microsoft/ApplicationInsights-Java/releases/download/${VERSION}/|g"

      - name: Create pull request against azure-docs-pr
        env:
          VERSION: ${{ inputs.version }}
          # this is the personal access token used for "gh pr create" below
          GITHUB_TOKEN: ${{ secrets.AARON_MAXWELL_TOKEN }}
        run: |
          message="Update the applicationinsights-java version to $VERSION"
          body="Update the applicationinsights-java version to \`$VERSION\`.

          cc @AaronMaxwell @heyams @jeanbisutti @mattmccleary @trask
          "
          branch="update-applicationinsights-java-to-${VERSION}"

          # gh pr create doesn't have a way to explicitly specify different head and base
          # repositories currently, but it will implicitly pick up the head from a different
          # repository if you set up a tracking branch

          git checkout -b $branch
          git commit -a -m "$message"
          git push --set-upstream origin $branch
          gh pr create --title "$message" \
                       --body "$body" \
                       --repo MicrosoftDocs/azure-docs-pr \
                       --base main
